---
title: "mirna"
author: "Garima Sood"
date: "May 11, 2018"
output: html_document
---

```{r}
#source("https://bioconductor.org/biocLite.R")
#biocLite("edgeR")

library(RColorBrewer)
#library(genefilter)
library(edgeR)
library(ggplot2)
library(knitr)
library(limma)
library(cvxbiclustr)
```


```{r}

mirna <- read.csv("C:/Users/garim/Documents/Capstone/Full data/Normalized/mirna_BRCA_01_11_snip.csv")

rownames(mirna) = mirna[,1]
mirna = mirna[,2:ncol(mirna)]
mirna_mat <- data.matrix(mirna)
```


```{r}
dim(mirna_mat)
```

```{r}
mirna_mat <- mirna_mat - mean(mirna_mat)
mirna_mat <- mirna_mat/norm(mirna_mat)

```


```{r}
## Create annotation for heatmap

types <- colnames(mirna)
ty <- as.numeric(factor(types))
cols <- rainbow(4)
YlGnBu5 <- c('#ffffd9','#c7e9b4','#41b6c4','#225ea8','#081d58')
hmcols <- colorRampPalette(YlGnBu5)(256)

```


```{r}
## Construct weights and edge-incidence matrices
phi <- 0.5; k <- 5
wts <- gkn_weights(mirna_mat,phi=phi,k_row=k,k_col=k)
w_row <- wts$w_row
w_col <- wts$w_col
E_row <- wts$E_row
E_col <- wts$E_col

```


```{r}
## Connected Components of Row and Column Graphs
wts$nRowComp
wts$nColComp
#### Initialize path parameters and structures
nGamma <- 5
gammaSeq <- c(11000,15000,18000, 22000, 25000, 30000)
## Generate solution path
sol <- cobra_validate(mirna_mat,E_row,E_col,w_row,w_col,gammaSeq)
verr <- sol$validation_error
ix <- which.min(verr)
heatmap(sol$U[[ix]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
rbind(verr, gammaSeq)
```

```{r}
gammaSeq <- c(17000,17500, 17800, 18200, 18600, 19000)
## Generate solution path
sol <- cobra_validate(mirna_mat,E_row,E_col,w_row,w_col,gammaSeq)
verr <- sol$validation_error
ix <- which.min(verr)
heatmap(sol$U[[ix]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
rbind(verr, gammaSeq)
```
```{r}
gammaSeq <- c(17950, 17970, 17990,18000, 18020,18050, 18070 )
## Generate solution path
sol <- cobra_validate(mirna_mat,E_row,E_col,w_row,w_col,gammaSeq)
verr <- sol$validation_error
ix <- which.min(verr)
heatmap(sol$U[[ix]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
rbind(verr, gammaSeq)
```

```{r}
gammaSeq <- c(17998, 17999, 18000, 18001,18002 )
## Generate solution path
sol <- cobra_validate(mirna_mat,E_row,E_col,w_row,w_col,gammaSeq)
verr <- sol$validation_error
ix <- which.min(verr)
heatmap(sol$U[[ix]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
rbind(verr, gammaSeq)
```

```{r}

## k =5
gammaSeq <- c(17999, 18000, 18001)
## Generate solution path
sol <- cobra_validate(mirna_mat,E_row,E_col,w_row,w_col,gammaSeq)
verr <- sol$validation_error
ix <- which.min(verr)
heatmap(sol$U[[ix]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
rbind(verr, gammaSeq)
```

```{r}
tmirna = t(mirna)
colnames(tmirna) <- rownames(mirna)
tmirna <- as.data.frame(apply(tmirna, 2, function(x) as.numeric(x)))
rownames(tmirna) <- colnames(mirna)
```

```{r}
varcol = apply(tmirna, 2, function(x) var(x))
rem_col <- which(varcol==0)
rem_col
```

```{r}
tmirna_sc <- scale(tmirna[,-rem_col], center = TRUE, scale = TRUE)
pc_tmirna <- prcomp((tmirna_sc), retx = TRUE)
```


```{r}
plot(pc_tmirna, type = "l")
vars <- apply(pc_tmirna$x, 2, var)
props <- vars / sum(vars)
plot(1:500, cumsum(props)[1:500])
```

```{r}
var_exp <- as.data.frame(t(rbind(var = pc_tmirna$sdev^2*100/sum(pc_tmirna$sdev^2),
                                 cum_var= cumsum(pc_tmirna$sdev^2*100/sum(pc_tmirna$sdev^2)))))

plot(1:10, var_exp$cum_var[1:10] , type = "l", main = "Scree Plot for Train data", ylab = "% total variance")

```


```{r}

rna <- read.csv("C:/Users/garim/Documents/Capstone/Full data/Normalized/rna_norm_log_counts_brca.csv")
rownames(rna) = rna[,1]
rna = rna[,2:ncol(rna)]
rna_mat <- data.matrix(rna)
```


```{r}
trna = t(rna)
colnames(trna) <- rownames(rna)
trna <- as.data.frame(apply(trna, 2, function(x) as.numeric(x)))
rownames(trna) <- colnames(rna)

```
 
```{r}
varcol = apply(trna, 2, function(x) var(x))
rem_col <- which(varcol==0)
rem_col
```

```{r}
trna_sc <- scale(trna, center = TRUE, scale = TRUE)
pc_trna <- prcomp((trna_sc), retx = TRUE)
```


```{r}
plot(pc_trna, type = "l")
vars <- apply(pc_trna$x, 2, var)
props <- vars / sum(vars)
plot(1:500, cumsum(props)[1:500])

```









